//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inceptum.WebApi.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inceptum.WebApi.Help.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of elements of type {0}.
        /// </summary>
        internal static string CollectionDocumentationTemplate {
            get {
                return ResourceManager.GetString("CollectionDocumentationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type: {0}.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data types.
        /// </summary>
        internal static string DataTypes_Title {
            get {
                return ResourceManager.GetString("DataTypes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value is {0}.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dictionary of {0} keyed by {1}.
        /// </summary>
        internal static string DictionaryDocumentationTemplate {
            get {
                return ResourceManager.GetString("DictionaryDocumentationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request - The request cannot be fulfilled due to bad syntax..
        /// </summary>
        internal static string ErrorCodes_400 {
            get {
                return ResourceManager.GetString("ErrorCodes_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized - Not authorized to access resource without auhtentication..
        /// </summary>
        internal static string ErrorCodes_401 {
            get {
                return ResourceManager.GetString("ErrorCodes_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden - Forbidden to access resource..
        /// </summary>
        internal static string ErrorCodes_403 {
            get {
                return ResourceManager.GetString("ErrorCodes_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found - Resource not found..
        /// </summary>
        internal static string ErrorCodes_404 {
            get {
                return ResourceManager.GetString("ErrorCodes_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Not Allowed - You tried to access a resource with an invalid method..
        /// </summary>
        internal static string ErrorCodes_405 {
            get {
                return ResourceManager.GetString("ErrorCodes_405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Acceptable - You requested a format that isn&apos;t supported..
        /// </summary>
        internal static string ErrorCodes_406 {
            get {
                return ResourceManager.GetString("ErrorCodes_406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gone - The resource requested has been removed from the server..
        /// </summary>
        internal static string ErrorCodes_410 {
            get {
                return ResourceManager.GetString("ErrorCodes_410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Many Requests - Incomming request rate is to high, slow down..
        /// </summary>
        internal static string ErrorCodes_429 {
            get {
                return ResourceManager.GetString("ErrorCodes_429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error - Some error occured on the server-side..
        /// </summary>
        internal static string ErrorCodes_500 {
            get {
                return ResourceManager.GetString("ErrorCodes_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable -  The service is temporarially offline for maintanance..
        /// </summary>
        internal static string ErrorCodes_503 {
            get {
                return ResourceManager.GetString("ErrorCodes_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error codes.
        /// </summary>
        internal static string ErrorCodes_Title {
            get {
                return ResourceManager.GetString("ErrorCodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A key/value pair where the key is of type {0} and value is of type {1}.
        /// </summary>
        internal static string KeyValuePairDocumentationTemplate {
            get {
                return ResourceManager.GetString("KeyValuePairDocumentationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length: {0}.
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length: {0}.
        /// </summary>
        internal static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range: inclusive between {0} and {1}.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching regular expression pattern: {0}.
        /// </summary>
        internal static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String length: inclusive between {0} and {1}.
        /// </summary>
        internal static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
    }
}
